[project]
name = "jooh-github-io"
version = "0.1.0"
description = "Personal website"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "altair",
  "altair-data-server",
  "altair-saver",
  "altair-viewer",
  "black",
  "cairosvg",
  "ghp-import",
  "jupyterlab",
  "matplotlib",
  "nbdime",
  "notebook",
  "pandas",
  "pelican",
  "pelican-gist",
  "pelican-jupyter",
  "pytest",
  "scipy",
  "seaborn",
  "smartypants",
  "typogrify",
]
