# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: jooh/jooh.github.io
  branch: source

media_folder: "/content/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "/content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    frontmatter_delimiter: ""
    fields:
      - { label: "Title", name: "Title", widget: "string" }
      - { label: "Date", name: "Date", widget: "datetime", format: "YYYY-MM-DD HH:mm" }
      - { label: "Tags", name: "Tags", widget: "string", required: false, hint: "Comma-separated tags." }
      - { label: "Summary", name: "Summary", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
